sudo: required
language: python
python: "3.8"

install:
  - pip install -r requirements.txt

jobs:
  include:
    - name: "tests"
      script:
        - cd tests
        - python3 -m unittest -v preprocess_test
        - python3 -m unittest -v generator_test

notifications:
  email: false